name: Build and Release EXE

on:
  workflow_dispatch:
    inputs:
      tag_name:
        description: 'Tag or version (e.g. v1.0.3)'
        required: true
        default: 'v1.0.0'
  push:
    tags:
      - 'v*' # trigger on tag v1.0.0

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Restore NuGet packages
      run: nuget restore VaMResourceManager.sln

    - name: Build with MSBuild
      run: msbuild VaMResourceManager.csproj /p:Configuration=Release
      
    - name: Show full project tree after build
      shell: pwsh
      run: |
        Write-Host "`n📁 Full project tree:"
        Get-ChildItem -Recurse -Force | ForEach-Object {
          $depth = ($_.FullName -replace [regex]::Escape((Get-Location).Path), "").Split([IO.Path]::DirectorySeparatorChar).Count - 1
          ('  ' * $depth) + $_.Name
        }
      
    - name: Create ZIP from build output
      run: |
        mkdir out
        copy VaMResourceManager\VaMResourceManager\bin\Release\VaMResourceManager.exe out\
        powershell Compress-Archive -Path out\* -DestinationPath VaMResourceManager.zip

    - name: GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ github.event.inputs.tag_name || github.ref_name }}
        name: ${{ github.event.inputs.tag_name || github.ref_name }}
        body: 'Automatic release'
        files: VaMResourceManager.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
